name: ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - run: jshell --show-version JDK-8225773.jsh

  jupiter-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - run: jshell --show-version -R-Dorg.junit.jupiter.api=org.junit.jupiter.api JDK-8225773.jsh
      continue-on-error: true

  jupiter-params:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - run: jshell --show-version -R-Dorg.junit.jupiter.params=org.junit.jupiter.params JDK-8225773.jsh
      continue-on-error: true

  platform-console:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - run: jshell --show-version -R-Dorg.junit.platform.console=org.junit.platform.console JDK-8225773.jsh
      continue-on-error: true
